services:
  - type: web
    name: extrator-atributos-web
    runtime: python
    pythonVersion: "3.11.11"
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: TRUE
      - key: STREAMLIT_SERVER_HEADLESS
        value: TRUE
    plan: free
    healthCheckPath: /_healthcheck
    autoDeploy: true

cache:
  paths:
    - /opt/render/.cache/pip
